### ISSUE TITLE
Move code into repo

### ISSUE THREAD

**Issue by gbinal** [GSA/gsa-doc-digital-signature#1]

**Comment by gbinal** [comment]
Sorry for the initial mistype.   What are your thoughts on sharing the source code directly in the reepo?

**Comment by lachellel** [comment]
@gbinal 

that is the intent!  I've asked for it to be committed (it's sitting in the labs right now)

It's being cleaned up a bit

**Comment by CinnyaSm** [comment]
Once it is cleaned up and ready go ahead and share.

**Comment by gbinal** [comment]
Great!  Holler if you need any help.  Do you have a rough ETA?

**Comment by lachellel** [comment]
@djpackham 

Any ETA on when you might have time to commit the source code for the dig sig tools?

**Comment by djpackham** [comment]
I should be able to commit the code today. Just need to find a minute to run the git commands:)

**Comment by jungshadow** [comment]
Just adding a :+1: to this issue. Any update on the ETA?

**Comment by lachellel** [comment]
Code committed; readme, contributing and licensing added;
