### ISSUE TITLE
Encryption feature?

### ISSUE THREAD

**Issue by mmaraya** [GSA/gsa-doc-digital-signature#26]
How much work would it take to add the ability to encrypt files?

**Comment by grandamp** [comment]
@mmaraya [There is already a tool from DoD that does that.](https://www.spi.dod.mil/ewizard.htm)  ;)

**Comment by lachellel** [comment]
Too much work?  :smile:

Encryption for **PIV** is a 1:N event.  
And it requires peering into any trust stores (local) / local key chains / global address lists or something like KT (key transparency <- very interesting).  There are approaches for encryption in the M:N person to person scenarios.  Tackling why _Johnny Can't Encrypt_ might be a bit much for a tool originally designed for signing docs for Federal Register.  

[In other words, designed differently from the get go.]  

I could be wrong of course!

**Comment by mmaraya** [comment]
Thanks for the quick and awesome responses! We'll look into the DoD encryption wizard.
